apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.accommodation.service.name | default "accommodation-service" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  ports:
  - port: {{ .Values.accommodation.service.port | default 8080 }}
    targetPort: {{ .Values.accommodation.service.port | default 8080 }}
  selector:
    app: {{ .Values.accommodation.deployment.name | default "accommodation" }}
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.accommodation.deployment.name | default "accommodation" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  replicas: {{ .Values.accommodation.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.accommodation.deployment.name | default "accommodation" }}
  template:
    metadata:
      labels:
        app: {{ .Values.accommodation.deployment.name | default "accommodation" }}
    spec:
      containers:
      - name: accommodation-service
        image: bukiteasy/accommodation-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.accommodation.deployment.containerPort | default 8080 }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.global.netEnv | default "Development" }}
        volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
            - name: elasticsearch-secrets
              mountPath: /app/certs/apm-server.crt
              subPath: apm-server.certificate
      volumes:
        - name: config-volume
          configMap:
            name: accommodation-service-config
        - name: elasticsearch-secrets
          secret:
            secretName: elasticsearch-secrets
