apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.filebeat.service.name | default "filebeat" }}
  namespace: {{ .Values.global.namespace | default "devops" }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.filebeat.deployment.name | default "filebeat" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  replicas: {{ .Values.filebeat.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.filebeat.deployment.name | default "filebeat" }}
  template:
    metadata:
      labels:
        app: {{ .Values.filebeat.deployment.name | default "filebeat" }}
    spec:
      serviceAccountName: {{ .Values.filebeat.service.name | default "filebeat" }}
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.15.0
          command: ["filebeat", "-e", "--strict.perms=false"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elk-secrets
                  key: ELASTIC_USERNAME
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elk-secrets
                  key: ELASTIC_PASSWORD
            - name: KIBANA_HOST_PORT
              value: "https://elasticsearch:5601"
            - name: ELASTICSEARCH_HOST_PORT
              value: "https://elasticsearch:9200"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varrundockersock
              mountPath: /var/run/docker.sock
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: filebeat-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varrundockersock
          hostPath:
            path: /var/run/docker.sock
