apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.service.name | default "kibana" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.kibana.deployment.name | default "kibana" }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.kibana.service.port | default 5601 }}
      targetPort: {{ .Values.kibana.service.port | default 5601 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.deployment.name | default "kibana" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  replicas: {{ .Values.kibana.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.kibana.deployment.name | default "kibana" }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.deployment.name | default "kibana" }}
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: KIBANA_PORT
              value: "5601"
            - name: ELASTICSEARCH_HOST_PORT
              value: "https://elasticsearch:9200"
            - name: KIBANA_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kibana-token-secret
                  key: KIBANA_SERVICE_ACCOUNT_TOKEN
          ports:
            - containerPort: {{ .Values.kibana.deployment.containerPort | default 5601 }}
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            - name: kibana-secrets
              mountPath: /certs/kibana.crt
              subPath: kibana.certificate
            - name: kibana-secrets
              mountPath: /certs/kibana.key
              subPath: kibana.key
            - name: kibana-secrets
              mountPath: /certs/ca.crt
              subPath: elastic.ca
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
        - name: kibana-secrets
          secret:
            secretName: elasticsearch-secrets
