apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: devops
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          host: ${NODE_NAME}

      - rename:
          fields:
            - from: "kubernetes.container.name"
              to: "service.name"

      - drop_event.when:
          or:
          - equals:
              kubernetes.container.name: "filebeat"
          - equals:
              kubernetes.labels.app: "filebeat"

    output.logstash:
      hosts: ["logstash:5044"]

    setup.kibana:
      host: '${KIBANA_HOST_PORT}'
      username: '${ELASTIC_USERNAME}'
      password: '${ELASTIC_PASSWORD}'

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: '${ELASTICSEARCH_HOST_PORT}'
        username: '${ELASTIC_USERNAME}'
        password: '${ELASTIC_PASSWORD}'

    http.enabled: true
    http.host: 0.0.0.0
    http.port: 5066