apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user.service.name | default "user-service" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  selector:
    app: {{ .Values.user.deployment.name | default "user" }}
  ports:
  - protocol: TCP
    port: {{ .Values.user.service.port | default 8080 }}
    targetPort: {{ .Values.user.service.port | default 8080 }}
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user.deployment.name | default "user" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  replicas: {{ .Values.user.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.user.deployment.name | default "user" }}
  template:
    metadata:
      labels:
        app: {{ .Values.user.deployment.name | default "user" }}
    spec:
      containers:
        - name: user-service
          image: bukiteasy/user-service:0.0.1
          ports:
            - containerPort: {{ .Values.user.deployment.containerPort | default 8080 }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.global.netEnv | default "Development" }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
            - name: secrets-volume
              mountPath: /app/secrets
            - name: elasticsearch-secrets
              mountPath: /app/certs/apm-server.crt
              subPath: apm-server.certificate
      volumes:
        - name: config-volume
          configMap:
            name: user-service-config
        - name: secrets-volume
          secret:
            secretName: user-service-secrets
        - name: elasticsearch-secrets
          secret:
            secretName: elasticsearch-secrets
