apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: devops-rabbitmq

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: devops
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: devops-rabbitmq
  hostPath:
    path: "/mnt/data/rabbitmq" 