apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.service.name | default "client-service" }}
  namespace: devops
spec:
  selector:
    app: {{ .Values.client.deployment.name | default "client" }}
  ports:
  - protocol: TCP
    port: {{ .Values.client.service.port | default 3009 }}
    targetPort: {{ .Values.client.service.port | default 3009 }}
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.deployment.name | default "client" }}
  namespace: {{ .Values.global.namespace | default "devops" }}
spec:
  replicas: {{ .Values.client.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.client.deployment.name | default "client" }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.deployment.name | default "client" }}
    spec:
      containers:
      - name: {{ .Values.client.deployment.name | default "client" }}
        image: bukiteasy/client:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.client.deployment.containerPort | default 3009 }}
        env:
        - name: NODE_ENV
          value: {{ .Values.global.nodeEnv | default "production" }}
        - name: PUBLIC_USER_SERVICE_BASE_URL
          value: "/user-service"
        - name: PUBLIC_NOTIFICATION_SERVICE_BASE_URL
          value: "/notification-service"
        - name: PUBLIC_ACCOMMODATION_SERVICE_BASE_URL
          value: "/accommodation-service"
        - name: PUBLIC_REVIEW_SERVICE_BASE_URL
          value: "/review-service"
        - name: PUBLIC_FIREBASE_API_KEY
          value: "AIzaSyAcqTxexa9D0ehQwSiUAoFY5jvrlucOb94"
        - name: PUBLIC_FIREBASE_AUTH_DOMAIN
          value: "buk-it-easy-dev.firebaseapp.com"
        - name: PUBLIC_FIREBASE_PROJECT_ID
          value: "buk-it-easy-dev"
        - name: PUBLIC_FIREBASE_STORAGE_BUCKET
          value: "buk-it-easy-dev.appspot.com"
        - name: PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          value: "238386706283"
        - name: PUBLIC_FIREBASE_APP_ID
          value: "1:238386706283:web:0f36ec71441bf8b746be2e"
        - name: PUBLIC_FIREBASE_MEASUREMENT_ID
          value: "G-VP6E1Z1NJN"