apiVersion: v1
kind: Service
metadata:
  name: accommodation-service
  namespace: devops
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: accommodation
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accommodation
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accommodation
  template:
    metadata:
      labels:
        app: accommodation
    spec:
      containers:
      - name: accommodation-service
        image: bukiteasy/accommodation-service:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
      volumes:
        - name: config-volume
          configMap:
            name: accommodation-service-config
