apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: devops
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: notification
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification-service
        image: bukiteasy/notification-service:0.0.1
        imagePullPolicy: Always  # This forces the image to be pulled every time
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
            - name: elasticsearch-secrets
              mountPath: /app/certs/apm-server.crt
              subPath: apm-server.certificate
      volumes:
        - name: config-volume
          configMap:
            name: notification-service-config
        - name: elasticsearch-secrets
          secret:
            secretName: elasticsearch-secrets
